---
title: "toDo"
author: "Robert Lee"
date: "July 28, 2015"
output: pdf_document
---

July 28th 2015

Data frame vs. matrix + vectors
Document what is needed.
      Give default plus way to override.  
      Those who will use will only use if few changes are necessary to get what they already do to 
      Make so that beginners can use, experts can customize.
            Don't make beginner enter unnecessary things.  Don't make experts do things your way.
      
/Store notes as part of package.      

Plan:
      Carry out operations with real data from old term.  If all works, great; otherwise, need changes.
      Then write up description of how to do.
      Then merge with Sweavetest package. 
      Might be easier to make this a package used by Sweavetest.
            Transition to database at leisure.

Generally, make lots of commits; when you get something working, commit.
Try not to have package on GitHub not working.
      Sometimes, better to commit before working in case you would lose much work.
      Try to have build, tests before committing.
            Put a whole bunch of these in tests directory.
      
Automated testing
Version with R
      Directory in package called tests
            If Any scripts in there generate error, fail.
            Anything can go in those files.
            Eg. run through example with known answer; stop if not expected answer.
      Requires thinking what should go into tests.
Several frameworks/ packages for unit tests.
      Some love them.
      Make it easier to handle checks?
      Eg. Do this and you should generate and error/ warning, / answer should be x.
            Must not generate error if you make the right kind of error, etc.
      Eg. **testthat, testPackage (Murdoch only)
      library(testthat)
Check with Hadley on testthat use.
Roxygen has some support for testthat?
It might automatically run the tests.
      

Test-based design.
Must understand user view from the beinning.
Tests important.  Tets first?  Less certain.
      Always have examples.  Make sure they produce right answer.*******
Tests that are good for testing are not necessarily good for examples.  ***
      Throw testthat in to examples at the end.
      
Go through check output, fix what can be fixed.
        

********


August 4th 2015

Maybe add fraction of given # option to IDToQuestionsAsked/ Answered/ Combined?


/No way to delete row by rownumber
/Give each row an ID?

/Option to overwrite course.db in createDB()

/Be more flexible with how to update database.
/      Another argument to update students (columns or something)
/      columns default= ID = 1, ...
/      Or named columns rather than numbered
/            columns = c(..., . )
/      columns = c(ID= "ID", email = "email", ...)
/      How flexible?  Only update certain columns.
/            Try with all.

/I choose names for things in database, but make it easy for people to import things into /database.
/      Import things with different names should work.
/      Data.frames can have more columns, in differnt orders, but MUST have columns I need.  
/      students: always need ID, names, email; not necessary to include program, notes.
/            Make it possible to enter, but not required.
            
/Flip necessaryness of assignmentNumber of date for assignments, etc.
/Same with examName
/More general: examName, assignmentName, not examNumber, assignmentNumber

/classParticpation basically entirely optional
/      Good to have, but implementation won't worry too much.



/Create standard empty database.
/      Import data afterwards.
      
      
Spend time on manual.
      Don't be complete.
      Start out really basically.
      Here's a typical workflow. (One possible workflow -- someone starting out, doing simple things.)
            Here's how you enter students.
                  Enter more, do this.
            Enter assignemnts , do this
            Enter ...
            Print out grades, do this.
      If I can't explain it, I should probably simplify it.

In namespace file as exported, users can see it.
      Can just export ones users use.
      start functionnames with a . if internal only.
      
      
Later, write functions for R beginners -- get stuff into data.frames

***********

August 6th 2015

/Mismatch between table and number of columns -- NA if columns not included.
/If too many columns included, ...not sure.

/query:
/createTable() <- table name, column names, etc.
/Empty data.frame
/df <- data.frame(ID = character(0))

****
Mysterious 
*Error in NextMethod() : object 'ID' not found*
when I try to make a dataframe directly without first naming the vectors.
****

/Check whether NA/ NULL/ Empty values mess up class participation/ attendance calculations.


****
August 11th 2015

/Add more flexibility to column names in entries.R functions.
/Function that seperates names into givenNames and lastName.

/Ran into bug with old TestMarks() function while trying to write QuickIntro; fix today.

/Rename column names to names that will surely work with SQL -- don't include \., \_.
/Clean up input initially -- want nice, easy to understand form.
/Be flexible in initial allowable input -- but then make it inflexible very very soon.
/Outside world is a mess, inside world is nice and predictable.

/Replace row deletion with row ghosting -- marked as deleted, but undoable.
/How to structure the deletions?
      Eg. delete records ID > 3, 2506 < ID  < 2510, etc.
      Check which records meet requirements
      Ask whether to delete, then mark as deleted if confirmed.

/add feature:  Just so you know, you just updated a row in "students"

*****
August 13th 2015

/Saying ID < 123456789 is diffucult; stored as characters.  Same for most values.  Dates /different.  Implement? See below

/ghostRow()
/deleteRow()
/Better names?

/Why, when I compile the QuickIntro, does it not act like I've built coursedb?
/No replicability

/out of bounds error: columns[["assignmentNames"]]
/Doesn't have a name yet as input to UpdateTable()
/Give them columns, vitalColumns names beofe calling UpdateTable()

/want an error message if a student doesn't have an ID.

/function: show me what you know about so-and-so.

**/Want better way to display data. # sort of done?  For assignments and students as a whole

/Can attach a class to output of a function
/class(result) <- c("assignmentData", class(result))
/Use reshape or plyr to reshape the data into... wide format

There is a fix() function!


random errors --> probably a scoping problem -- two variables, usually the same but not always; when not, problems.

/more notes for deleting

/delete(~ID>3)  <-- not evaluated yet, evaluated later in proper context. 
/Give vector of trues, falses, identifying who gets deleted -- or, give a formula identifying /who gets deleted.  Starts with a ~, then columns of table
/x <- 10
/fla <- ~ grade < x
/env <- list2env(df, parent = environment(fla))
/eval(fla[[2]], envir = env)
/If it doesn't find x in that environment, it'll look in the parent.  Environment of the /forumula --> context where it was defined.
/"User can write an expression that selects... individuals... another delete selection."
/     Note: environments for evaluating formula.
*****
August 18th 2015

Make functions work without inputs (ie. empty tables?)
/showStudents include name, email
/Use class, print method
/Call class studentInfo, print.studentInfo method

/showtest : per test: specify student, test
/      reformat processed 
/      mostly want to know right or wrong
/            sometimes actual answers
/how did class do overall?
/      score for every student
/      answer for every question for every student?
/read scores on each question
/      input identifies test
/            one line per student, how they did on each question on test
/            students are rows, questions are columns
/            add class to result, printmethod for class
/            mod dataframe to add student, print
            
******
August 25th 2015
/Change fail to warning in showTest()
/Give error: student not found
/if I can make functions recoverable -- X and Y  failed, but rest works -- leave course.db /alone; otherwise, delete malfunctioning lines.
finish automated checking stuff

*****
September 1st 2015
/Automated checking problem:
/      !Examples use sample database?
/      If users have no existing, create one.
/            Put this into example code.  
            In dbCONN() fails, connect to existing .db created with package.  
            Put .db in inst directory?  Copy to temp file, use that?
            Connection to non-existing database --> creates database --> problem.
/      Distribute a tiny database for examples
/            Function -> copy to temp file, use sample database.  Put in inst directory.
/            set up sample database, on exit close it.
/            Maybe copy into a temp file, use that so we can do writes to it.
/            Close at end of example so user can use their own file again.
/      Getting very messy.
      
/tempdir() gives a writable directory
/tempfile() makes up a unique filename within directory.
/To always call database course.db, copy to tempdir()
/To give a new name every time, copy though tempfile()
/Guaranteed to be writable.  Normally, R will delete it at the end of the session, but R can /crash, they can sit around.
RSQLite may close connections automatically when it garbage connects the collection object.
Reassign new connection to the conn variable in dbCONN, old will be closed eventually.  Can force it to happen sooner.  Bad idea to have .db's in an unknown, indeterminate state.  
Figure out how to close them.  There is a dbDisconnect() function; call it on the connection.  

      Something topical and useful:
Doing stuff that works with webpages.
That involves using RMarkdown.
Be familiar with that.
      Next step: Shiny.
Put together by RStudio people.
Runs R on a server.  Has the server communicating with a webpage.  
I don't need to know about HTML, JavaScript; just run R, get an interactive webpage.
shiny.rstudio.com  
Useful for me to do.
Impresses people if I can do that.  
Snazzes things up really quickly.
      Possible to do in RMarkdown document?
No UI stuff, only server stuff.  
Put together webpage that displays course data.  Privacy issues, but possible.  
Do kind of thing you get with OWL online.  Go to database, grab data, show to people.  
      Web programming a pretty useful skill to have.  
More people doing this kind of stuff.  
NYT uses R for some graphics; not sure if interactive stuff.
A little slow, but working on that  